# 목차

- [목차](#목차)
- [시스템 오류 ERROR](#시스템-오류-error)
- [예외 EXCEPTION](#예외-exception)
	- [예외 클래스들](#예외-클래스들)
   	- [예외 클래스의 계층구조](#예외-클래스의-계층구조)
	- [checked exception vs unchecked exception](#checked-exception-vs-unchecked-exception)
	- [try-catch문](#try-catch문)
   	- [finally블럭](#finally블럭)
	- [try-with-resource문](#try-with-resource문)
	- [예외 발생시키기](#예외-발생시키기)
	- [예외 처리 미루기](#예외-처리-미루기)
	- [사용자 정의 예외 클래스](#사용자-정의-예외-클래스)
   	- [예외 되던지기](#예외-되던지기)
   	- [연결된 예외](#연결된-예외)
- [로그 남기기](#로그-남기기)
	- [logging](#logging)
	- [java.util.logging](#javautillogging)
	- [Logger 구현](#logger-구현)
	
<br>

# 프로그램에서의 오류
- 컴파일 오류(compile error) : 프로그램 코드 작성중 발생하는 문법적 오류, IDE환경에서 대부분 탐지 됨
- 실행 오류(runtime error) : 실행중인 프로그램이 의도하지 않은 동작(bug)을 하거나 실행 중지되는 오류. 비정상 종료시 심각한 오류가 발생할 수 있다.
- 논리적 오류 : 실행은 되지만, 의도와 다르게 동작하는 것

## 시스템 오류 ERROR

- 능력 밖의 오류. 자바가 동작하는 환경(JVM)에서 문제가 생긴 것.
- 동적 메모리가 없는 경우, 스택오버플로우, 메모리가 부족하거나 운영체제의 문제 등
- 프로그램 코드로 수습할 수 없는 심각한 오류
- 대비 불가능

<br>

## 예외 EXCEPTION

- 작성한 코드가 의도와 다른 상황에 직면했을 때
- 사용자의 예상치 못한 입력값, 읽으려고 했던 파일을 찾을 수 없는 문제, 네트워크나 DB 연결이 안되는 경우 등
- 개발자가 구현한 로직에서 발생한 실수나 사용자의 영향에 의해 발생
- 예상하지 못한 예외상황
- 프로그램 코드에 의해 대비 가능한 다소 미약한 오류
- 프로그램의 비정상 종료를 피하고 원활히 실행되도록 한다.
- 실행 오류가 발생한 경우 오류의 과정을 재현하는 것은 현실적으로 어렵기 때문에
- 오류가 발생한 경우 log를 남겨서 추후 log를 분석하고 원인을 파악하여 디버깅 하는 것이 중요

## 예외 클래스들

![image](https://user-images.githubusercontent.com/106129404/230388360-977f22c9-c41b-4cd3-9794-6109375bd147.png)
- 모든 예외클래스의 최상위 클래스는 Exception 클래스
- 자바에서는 다양한 예외들에 대해 처리를 위한 클래스가 제공되고 있다.
- Arithmetic Exception : 정수를 0 으로 나눈 경우 발생
- NullPointerException : 초기화 되지 않은 Object를 사용하는 경우
- ArrayIndexOutOfBoundsException : 배열의 크기를 넘어선 인덱스를 참조하려는 경우
- FileNotFoundException : 참조하는 파일이 지정된 위치에 존재하지 않는 경우
- ClassNotFoundException : 클래스가 (동적)로드되지 않는 경우

## 예외 클래스의 계층구조
![image](https://github.com/soberdam/TIL/assets/106129404/72b06fc3-8506-4855-8f93-baa4dcac26a1)
- 예외 클래스들은 Exception 클래스와 자손들, 그리고 RuntimeException 클래스와 그 자손들로 나눌 수 있다.
- RuntimeException 클래스들은 프로그래머의 실수에 의해 발생할 수 있는 예외들. 예외처리를 강제하지 않는다.
- Exception 클래스들은 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외들. 예외처리를 강제한다.


## checked exception vs unchecked exception

- **unchecked exception**은 try - catch문을 작성하지 않고 프로그램이 중간에 뻗더라도 일단 컴파일 후 실행된다. Runtime Exception 클래스와 그로부터 상속된 모든 Exception이다.
- **checked exception**은 try - catch문을 작성하지 않으면 아예 컴파일되지 않는다. Runtime Exception을 제외한 모든 Exception 클래스들이 checked exception에 속하며, checked exception은 **반드시 예외처리**를 해주어야 컴파일 할 수 있다.

## try-catch문
- 예기치 못한 예외의 발생에 대비한 코드를 작성하여, 프로그램의 비정상 종료를 막고 실행상태를 정상적으로 유지하도록 한다.
- try - catch문을 사용하여 예외상황 발생시 catch문을 실행하고 나머지 코드 실행 가능.
- try문 안의 코드들은 예외를 만났을 때 catch문으로 이동한다. (try문 내 나머지 코드는 실행 X)
- catch문도 순차적으로 실행되므로 위에 있는 catch문이 우선순위.
- Exception class는 다른 모든 Exception 관련 클래스들의 부모이다. 그러므로 Exception 클래스로 모든 예외를 모아 한번에 처리하는 것도 가능.
- Exception 클래스를 활용하여 default 처리를 할 때 catha문 블록들의 맨 마지막에 위치한다.(if-else에서 else와 유사)
- 예외가 발생하면, 발생한 예외에 해당하는 인스턴스가 생성되고 이 인스턴스가 catch문의 참조변수에 instanceof 연산을 하며 결과가 true인 catch문을 검사한다.
- 다만, 이러한 정보를 통해 코드의 내용이나 구조 등을 나쁜 의도를 가진 사람들에게 노출할 수도 있기 때문에 보통 이러한 정보를 사용자가 직접 볼 수 있게 구성하지는 않고, 서버 측에서 로그 파일 등을 이용해 관리자만 볼 수 있게 처리한다.
- finally문은 무조건 실행되는 블럭이다. 
- finally문은 소켓, 파일, 네트워크 등 리소스를 사용 후 닫을 때 주로 사용한다.
- 여러개의 예외가 발생하는 경우, 멀티 캐치 블럭으로 `|` 기호를 이용하여 하나로 묶어서 처리할 수도 있다. 멀티 캐치 블럭의 경우 연결 개수에는 제한이 없으나 예외들이 서로 조상과 자손 관계라면 컴파일 에러가 발생한다.
- 멀티 캐치 블럭으로 처리할 경우, catch블럭 내에서 실제로 어떤 예외가 발생한 것인지 알 수 없으므로 `|`기호로 연결된 예외클래스의 공통 조상 예외클래스에 선언된 멤버만 사용할 수 있다.
- 필요한 경우, instanceof로 어떤 예외가 발생한 것인지 확인하고 해당하는 참조변수로 인스턴스 e를 다운캐스팅하여 메소드를 호출할 수 있다.
- 멀티 캐치 블럭에 선언된 참조변수 e는 상수이므로 값을 변경할 수 없다.
```java
try {
test.loadClass("a.txt", "java.lang.String");
} catch (ExceptionA | ExceptionB e) {
	e.methodA // 에러.
	if(e instanceof ExceptionA) {
		ExceptionA e1 = (ExceptionA) e;
		e1.methodA(); // OK
	}
	e.printStackTrace;
}
```
- 각각의 예외를 따로 처리할 수도 있다.
```java
try {
test.loadClass("a.txt", "java.lang.String");
} catch {FileNotFoundException e) {
	e.printStackTrace;
} catch {ClassNotFoundException e) {
	e.printStackTrace;
}
```
- try-catch문 안에 try-catch문으로 중첩도 가능하다.

### getMessage()와 printStackTrace()
- catch문의 e 인스턴스 변수의 메소드를 활용할 수 있다.
- **getMessage()메소드**를 이용하면 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.
- **printStackTrace()메소드**를 사용하면 예외 발생 당시의 호출 스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
-  `printStackTrace(PrintStream s)` 또는 `printStackTrace(PrintWriter s)`를 사용하면 발생한 예외에 대한 정보를 파일에 저장할 수도 있다.

## finally블럭
- 예외의 발생 여부에 상관없이 실행되어야 할 코드를 포함한다.
- try블럭이나 catch블럭에서 `return`문이 실행되는 경우에도, finally블럭의 문장들이 먼저 실행된 후에 현재 메서드를 종료한다.
- try블럭과 finally블럭에서 모두 예외가 발생한 경우 마지막으로 발생한 예외인 finally 블럭의 예외만 출력된다. (try블럭 무시)

## try-with-resource문

- 외부 리소스들을 사용할 때에는 접근이 끝났을 때 close()를 해주어야 함
- 리소스를 사용하는 경우 close()를 사용하지 않아도 try를 벗어나는 순간 close()를 자동으로 호출한다.
- 리소스를 try() 내부에서 선언한다.
- 자바 9부터는 try() 외부에서 리소스를 선언하고 변수만을 `try(obj)`와 같이 사용할 수 있다.
- try-with-resource 문은 **try** 문에 괄호를 추가하여 그 안에 사용할 자원을 정의한다. **객체를 여러 개 선언할 수도 있고, 세미콜론(;)으로 구별한다.** 
- 전체 try 문(try, catch, finally 등)이 종료되면 생성된 인스턴스는 자동으로 종료되기 때문에 명시적으로 close를 이용하지 않는다.
- 해당 리소스 클래스가 AutoCloseable 인터페이스를 구현해야 한다.
- 만약 try문 내부와 resource의 close에서 모두 예외가 발생하는 경우, try블럭의 예외를 실제 발생한 예외로 하고 CloseException은 억제된(suppressed)예외로 다룬다.
- 억제된 예외의 정보는 실제 발생한 예외에 저장된다. (`getSuppressed()` 메소드로 접근 가능)
- FileInputStream의 경우에는 AutoCloseable을 구현하고 있다.

```java
import java.io.FileWriter;
import java.io.IOException;

public class TryWithResource {

	public static void main(String[] args) {
		FileWriter f = new FileWriter("data.txt")
		try (f) {
			f.write("Hello");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
```



## 예외 발생시키기 
- **thorw 키워드**를 사용하여 예외를 발생시킨다.
- `throw new Exception();`
- 코드에서 직접 예외를 발생시킬 때 사용
- 생성자에 String을 넣어주면 Exception 인스턴스에 메시지로 저장되어 `getMessage()`를 이용하여 다시 얻을 수 있다.

```java
public class MyException {

	public static void main(String[] args) {
		throw new RuntimeException("무언가 문제가 있습니다.");

	}

}
```


## 예외 처리 미루기
- 예외 처리는 예외가 발생하는 코드에서 **try블록을 사용**하거나 **코드를 사용하는 클래스에서 처리하도록 넘기는 방법**이 있다.
- **throws 키워드**를 사용하여 예외 처리를 미룰 수 있다.
- `public static void main(String[] args) throws IOException`
- 예외처리를 해당 클래스에서 할 필요가 없음
- 예외를 발생시키는 코드를 사용하는 클래스에서 처리하게 넘김
- 코드를 사용하는 클래스에서 해당 코드를 사용하는 문장에서 예외처리한다.
- 메서드의 선언부에 예외를 선언함으로써 메서드를 사용하려는 사람이 선언부를 보았을 때, 어떤 예외들을 처리해야 하는지 손쉽게 알 수 있다.
- 메서드를 사용하는 쪽에서 예외처리를 하도록 강제할 수 있다.
- 일반적으로 RuntimeException클래스들은 throws하지 않으며, 반드시 예외처리해야하는 Exception 클래스들을 미룰 때 선언한다.
- 어떤 클래스에서 예외처리를 할 것인지, 어떤 클래스에서 로그를 남길 것인지에 따라 판단
- main 메소드에서 throws 한다면 JVM에 예외를 넘기고, 프로그램이 중단될 수 있다.

```java
import java.io.FileWriter;
import java.io.IOException;

public class ThrowException {

	public static void main(String[] args) throws IOException {
		FileWriter f = new FileWriter("./data.txt");
		f.write("Hello");
		f.close();
	}

}
```

## 사용자 정의 예외 클래스
- JDK에서 제공하는 예외 클래스 외에 프로그래머가 직접 만들어야 하는 예외가 있다.
- 기존 예외 클래스중 가장 유사한 클래스를 상속받아 사용자 정의 예외 클래스를 생성한다.
- 잘 모르겠으면 기본적으로 최상위 예외 클래스인 Exception 클래스 혹은 RuntimeException 클래스를 상속할 수 있다.
- 사용자 정의 예외 클래스의 생성자에서 부모 예외클래스를 생성한다.
- 메시지를 저장하려면 String을 매개변수로 받는 생성자를 추가하여 부모 생성자를 호출한다.
- 
- 예외를 발생시킬 문장에서 throw 키워드를 사용하여 예외상황을 지정한다.

## 예외 되던지기
- 하나의 예외에 대해서 예외가 발생한 메서드와 이를 호출한 메서드 양쪽 모두에서 처리해줘야 할 작업이 있을 때 사용된다.
- 예외가 발생할 메서드에서 try-catch문을 사용함과 동시에 catch문에서 throw로 예외를 발생시키고, 메서드의 선언부에 throws로 호출 메서드에 예외를 전달한다.
- return값이 있는 메서드는 try문과 catch문 모두 return문이 있어야 하지만, 예외 되던지기를 하면 catch문 내부에 return문이 없어도 된다.

  ```java
  public static void main(String[] args) {
		try {
			method();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	static void method() throws Exception {
		try {
			throw new Exception();
		} catch (Exception e) {
			throw e;
		}
	}
   ```

## 연결된 예외
- 예외 A가 예외 B를 발생시켰다면, A를 B의 원인 예외(cause exception)이라고 한다.
- `B.initCause(A)`로 원인 예외를 등록하고, throw로 이 예외(B)를 던진다. 
- 여러가지 예외를 하나의 큰 분류로 묶어서 다루기 위해 사용
	- 조상으로 예외를 묶는다면 어떤 예외가 실제로 발생한 것인지 알 수 없다. 또한 상속관계를 변경해야 한다. 그러나 원인 예외는 상속관계가 아니어도 상관없다.
   ```java
   try {
			statInstall();
		} catch (SpaceException e) {
			InstallException ie = new InstallException("설치중 예외발생");
			ie.initCause(e);
			throw ie;
		}

   ```
- checked 예외를 unchecked 예외로 바꾸기 위해 사용
	- checked예외가 발생해도 예외를 처리할 수 없을 때, 의미없는 try-catch문을 추가하기보다 unchecked로 바궈 선택적으로 예외처리를 할 수 있다.
   	- RuntimeException의 생성자를 사용한다.
   ```java
   static void startInstall() throws SpaceException {
		if(!enoughMemory())
			throw new RuntimeException(new MemoryException("메모리가 부족합니다."));
	}
   ```
   
<br>

# 로그 남기기

## logging
- 시스템 운영에 대한 기록
- 오류가 발생했을 때 기록을 남겨 디버깅을 용이하게 함
- 로그파일에 기록하는 코드를 추가하여 필요한 정보가 로그로 남을 수 있도록 함
- 디버깅, 시스템에러 추적, 성능 향상, 문제점 개선등을 위해 사용
- 너무 적은 로그는 시스템의 상황을 파악하기 어렵고, 너무 많은 로그는 빈번한 File I/O 오버헤드와 로그파일의 백업 문제등이 발생

## java.util.logging
![image](https://user-images.githubusercontent.com/106129404/230540364-a798d6a4-a03b-4580-ad10-8e1c137fb779.png)

- java.util.logging.Logger를 활용하여 로그를 남긴다.
- 자바에서 기본으로 제공되는 log 패키지
- 파일이나 콘솔에 로그 내용을 출력할 수 있다.
- jre/lib/logging.properties 파일을 편집하여 로그의 출력방식, 로그 레벨을 변경 할 수 있음
- logging 패키지에서 제공하는 로그 레벨은 severe, warning, info, config, fine, finer, finest
- log4j와 같은 오픈소스를 주로 활용

## Logger 구현
1. Logger 인스턴스를 생성한다.
2. 로그를 남기기 위한 FileHandler를 생성한다.
3. FileHandler의 로그 level을 지정한다.
4. `addHandler()` 메소드로 Logger에 FileHandler를 추가한다.



